### PR TITLE
add new module 'pytz' and some updates on versions

### PR DESCRIPTION
**Pull request by huaweiyang94**
In the previous pull request, we introduced a new module 'pytz' in our script https://github.com/singer-io/tap-referral-saasquatch/pull/7. However, we did not include the module in setup.py, this pull request is for adding the missing module as well as update the versions of modules we are using.

### CODE REVIEW

**Comment by timvisher** [comment]
Thanks for being so on top of this. I just added pytz and released and it and will be monitoring for successful jobs.

The version bump for singer-python is pretty extreme. There were no conflicts between 1.x and 5.x that affected this tap?

**Comment by timvisher** [comment]
1.0.4 seems to do the trick. Can you resolve conflicts and provide some rationale for the rest of the version bumps?

Thanks! :)

**Comment by huaweiyang94** [comment]
Hi tim, thanks for the updates on pytz and I just solved the conflict. The reason I was bumping singer-python version was that we need its utils.now() method in the newer version. But since you have a workaround that replaces utils.now(), I think we are now good to keep the old versions. Also, the version update for "requests" does not seem necessary either.

**Comment by timvisher** [comment]
Good to know. Thanks for your contributions.

**Pull request closed without merging**
