### PR TITLE
Updated primary keys

### PR DESCRIPTION
**Pull request by jericmason**
The primary keys in the schema now match those in the script and have been updated to reflect the SaaSquatch primary keys.

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @jericmason, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @jericmason!

Thank you for signing the Singer Contribution License Agreement.

**Comment by briansloane** [comment]
Thanks for this contribution, @jericmason.  This looks like a valuable change to the tap. It will necessitate a major version bump since previously extracted data will not align with these changes. We can take care of that when reviewing and merging.

Can you point to any documentation or reference from SaaSquatch that shows the primary keys for this data? That will be helpful for any future questions.

**Comment by jericmason** [comment]
Thanks @briansloane, we haven't explicitly described our primary keys for the exports part of our API. It can implicitly be identified as the "required" fields in our "create or update user" https://docs.referralsaasquatch.com/api/methods/#create_user call. We also have this document that explains how our user / account Ids work. Hopefully this can be of some help.

**Pull request merged**
