### PR TITLE
CH: Adding dateConverted and programId to schema

### PR DESCRIPTION
**Pull request by CobeyH**
Saasquatch is updating their system to allow for the historic "Classic" program to be hidden. As part of this, new fields have been added to the schema.

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @CobeyH, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @CobeyH!

Thank you for signing the Singer Contribution License Agreement.

**Comment by CobeyH** [comment]
Good morning @cmerrick,

Is there any progress on getting this change merged into master. Please let me know if there is anything I can do to aid in the process.

**Comment by KAllan357** [comment]
@CobeyH Thanks for this!

**Pull request merged**
